  - name: Installation of openstack Cinder for Ubuntu
    apt:
      name:
        - cinder-volume
        - python3-mysqldb
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
